_id: cr7e1r9CK2mjXSB1
_key: '!items!cr7e1r9CK2mjXSB1'
img: systems/pf1/icons/feats/deceitful.jpg
name: Environmental Weapon
system:
  abilityType: ex
  associations:
    classes:
      - Vigilante
  description:
    value: >-
      <p>When the vigilante gains this talent, he must select one type of
      terrain from the ranger’s list of favored terrains. While in this terrain,
      as a swift action the vigilante can find an improvised weapon if there are
      any loose or moveable objects around (subject to the GM’s discretion). He
      doesn’t take a penalty for using these improvised weapons. For example, if
      the vigilante selected the urban environment, he might attack a foe with a
      chair, an empty bottle, or even a door.</p>

      <p>At 5th, 10th, 15th, and 20th levels, the vigilante can select an
      additional type of terrain.</p>
  subType: classFeat
type: feat

